apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prom-taller
    url: http://localhost:9090
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: "3.11.0"

  - name: Loki
    type: loki
    uid: loki-taller
    url: http://localhost:3100
    access: proxy
    jsonData:
      maxLines: 1000
